from mjlab.tasks.WMP.mdp.commands import WmpVelocityCommandCfg as WmpVelocityCommandCfg
from mjlab.tasks.WMP.mdp.curriculums import commands_vel as commands_vel
from mjlab.tasks.WMP.mdp.curriculums import terrain_levels_wmp as terrain_levels_wmp
from mjlab.tasks.WMP.mdp.metrics import mean_action_acc as mean_action_acc
from mjlab.tasks.WMP.mdp.observations import amp_observation as amp_observation
from mjlab.tasks.WMP.mdp.observations import base_ang_vel as base_ang_vel
from mjlab.tasks.WMP.mdp.observations import base_lin_vel as base_lin_vel
from mjlab.tasks.WMP.mdp.observations import builtin_sensor as builtin_sensor
from mjlab.tasks.WMP.mdp.observations import command as command
from mjlab.tasks.WMP.mdp.observations import depth_image as depth_image
from mjlab.tasks.WMP.mdp.observations import foot_contact as foot_contact
from mjlab.tasks.WMP.mdp.observations import foot_contact_forces as foot_contact_forces
from mjlab.tasks.WMP.mdp.observations import foot_height as foot_height
from mjlab.tasks.WMP.mdp.observations import forward_height_map as forward_height_map
from mjlab.tasks.WMP.mdp.observations import generated_commands as generated_commands
from mjlab.tasks.WMP.mdp.observations import height_scan as height_scan
from mjlab.tasks.WMP.mdp.observations import joint_pos_rel as joint_pos_rel
from mjlab.tasks.WMP.mdp.observations import joint_vel_rel as joint_vel_rel
from mjlab.tasks.WMP.mdp.observations import last_action as last_action
from mjlab.tasks.WMP.mdp.observations import projected_gravity as projected_gravity
from mjlab.tasks.WMP.mdp.observations import wm_prop as wm_prop
from mjlab.tasks.WMP.mdp.rewards import action_rate_l2 as action_rate_l2
from mjlab.tasks.WMP.mdp.rewards import base_height_l2 as base_height_l2
from mjlab.tasks.WMP.mdp.rewards import dof_acc_l2 as dof_acc_l2
from mjlab.tasks.WMP.mdp.rewards import dof_error_l2 as dof_error_l2
from mjlab.tasks.WMP.mdp.rewards import feet_air_time as feet_air_time
from mjlab.tasks.WMP.mdp.rewards import feet_edge as feet_edge
from mjlab.tasks.WMP.mdp.rewards import feet_slip as feet_slip
from mjlab.tasks.WMP.mdp.rewards import lin_vel_z_l2 as lin_vel_z_l2
from mjlab.tasks.WMP.mdp.rewards import self_collision_cost as self_collision_cost
from mjlab.tasks.WMP.mdp.rewards import stumble as stumble
from mjlab.tasks.WMP.mdp.rewards import track_angular_velocity as track_angular_velocity
from mjlab.tasks.WMP.mdp.rewards import track_linear_velocity as track_linear_velocity
from mjlab.tasks.WMP.mdp.rewards import upright as upright
from mjlab.tasks.WMP.mdp.terminations import bad_orientation as bad_orientation
from mjlab.tasks.WMP.mdp.terminations import illegal_contact as illegal_contact
from mjlab.tasks.WMP.mdp.terminations import (
  out_of_terrain_bounds as out_of_terrain_bounds,
)
from mjlab.tasks.WMP.mdp.terminations import time_out as time_out
from mjlab.envs.mdp.events import push_by_setting_velocity as push_by_setting_velocity
from mjlab.envs.mdp.events import reset_joints_by_offset as reset_joints_by_offset
from mjlab.envs.mdp.events import reset_root_state_uniform as reset_root_state_uniform
